# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qbdb', '0004_auto_20150427_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='part2_answer',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part2_answer_sanitized',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part2_text',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part2_text_sanitized',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part2_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part3_answer',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part3_answer_sanitized',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part3_text',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part3_text_sanitized',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part3_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part4_answer',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part4_answer_sanitized',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part4_text',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part4_text_sanitized',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part4_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part5_answer',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part5_answer_sanitized',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part5_text',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part5_text_sanitized',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part5_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part6_answer',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part6_answer_sanitized',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part6_text',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part6_text_sanitized',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='part6_value',
            field=models.IntegerField(default=0),
        ),
    ]
